### ISSUE TITLE
it is not working in gnome 3.34

### ISSUE THREAD

**Issue by jalberto** [jwendell/gnome-shell-extension-timezone#42]
- remote file is not working
- local file half works

![image](https://user-images.githubusercontent.com/99927/69445701-2a384980-0d53-11ea-972a-edb8e0427d4f.png)

```
gnome-shell[185558]: Error building an avatar cache for user UTC: Gio.IOErrorEnum: Error when getting information for file “/home/foo/http:/icons.iconarchive.com/icons/icojam/blue-bits/256/globe-icon.png”: No such file or directory
```

**Comment by jwendell** [comment]
Thanks for the bug report. I only had time to investigate this issue this week.
I pushed a fix, it should be available as an update soon via https://extensions.gnome.org.

**Comment by jalberto** [comment]
Thanks!

**Comment by jalberto** [comment]
@jwendell still not working for me, ther eis not errors now, but avatar still don't show up

**Comment by jalberto** [comment]
```
Feb 06 11:35:54 mido-wonderlan gnome-shell[2190]: Error building an avatar cache for user Oscar: Gio.IOErrorEnum: Error when getting information for file “/home/ja/http:/cdn.libravatar.org/avatar/d644796e500690ddfe3beb6cb2aabf59”: No such file or directory
Feb 06 11:35:54 mido-wonderlan gnome-shell[2190]: Error building an avatar cache for user UTC: Gio.IOErrorEnum: Error when getting information for file “/home/ja/http:/icons.iconarchive.com/icons/icojam/blue-bits/256/globe-icon.png”: No such file or directory
```

**Comment by jwendell** [comment]
Weird... for some reason the extension page shows only version up to 3.32: https://extensions.gnome.org/extension/1060/timezone/

So, I believe you are not running the new, updated version of this extension.

Need to investigate why 3.34 does not show up there... If you have any hint, please tell me!

**Comment by jalberto** [comment]
I tried to install it manually, but even if the code is in the correct
directory `gnome-extensions list` don't show it up :/
